### ISSUE TITLE
claiming command, fees

### ISSUE THREAD

**Issue by Golddouble** [ymgve/bitcoin_fork_claimer#31]
I want to claim BCH.

So I have this address for claiming BCH:
1Pv17qmWEANskhVr4PTNd73sc87CWjMPAh

When I have a look at the Block Explorer:
https://blockchain.info/address/1Pv17qmWEANskhVr4PTNd73sc87CWjMPAh
there are two transactions:
c7ad778f0197f4750813900d207e6ee4c416d9f699906074a8a3598a23450c4b and
bdb96a71881780b5622b9ab4a382f207e6d6514d6a5cc5dfa0ccafe243662f79

A) Do I have to make two commands to claim all BCH like:
```
python claimer.py BCH c7ad778f0197f4750813900d207e6ee4c416d9f699906074a8a3598a23450c4b PRIV_KEY_OF_1Pv17qmWEANskhVr4PTNd73sc87CWjMPAh 1Pv17qmWEANskhVr4PTNd73sc87CWjMPAh BCH_ADDR
python claimer.py BCH bdb96a71881780b5622b9ab4a382f207e6d6514d6a5cc5dfa0ccafe243662f79 PRIV_KEY_OF_1Pv17qmWEANskhVr4PTNd73sc87CWjMPAh 1Pv17qmWEANskhVr4PTNd73sc87CWjMPAh BCH_ADDR

```
B) Or is it enough to only make one command to claim all BCH's like:
```python claimer.py BCH c7ad778f0197f4750813900d207e6ee4c416d9f699906074a8a3598a23450c4b PRIV_KEY_OF_1Pv17qmWEANskhVr4PTNd73sc87CWjMPAh 1Pv17qmWEANskhVr4PTNd73sc87CWjMPAh BCH_ADDR```

C) If I have to make two commands (like A) ), do I have to pay transaction fees twice?

Would appreciate your answers. Thank you.

With kind regards
Golddouble

**Comment by avialias** [comment]
Why dont you claim bhc with coinomi app?
It works..you just sweep adress...than you can exchange or send it from
android to your hw or local wallet.

I want to claim BCH.

So I have this address for claiming BCH:
1Pv17qmWEANskhVr4PTNd73sc87CWjMPAh

When I have a look at the Block Explorer:
https://blockchain.info/address/1Pv17qmWEANskhVr4PTNd73sc87CWjMPAh
there are two transactions:
c7ad778f0197f4750813900d207e6ee4c416d9f699906074a8a3598a23450c4b and
bdb96a71881780b5622b9ab4a382f207e6d6514d6a5cc5dfa0ccafe243662f79

A) Do I have to make two commands to claim all BCH like:

python claimer.py BCH
c7ad778f0197f4750813900d207e6ee4c416d9f699906074a8a3598a23450c4b
PRIV_KEY_OF_1Pv17qmWEANskhVr4PTNd73sc87CWjMPAh
1Pv17qmWEANskhVr4PTNd73sc87CWjMPAh BCH_ADDR
python claimer.py BCH
bdb96a71881780b5622b9ab4a382f207e6d6514d6a5cc5dfa0ccafe243662f79
PRIV_KEY_OF_1Pv17qmWEANskhVr4PTNd73sc87CWjMPAh
1Pv17qmWEANskhVr4PTNd73sc87CWjMPAh BCH_ADDR


B) Or is it enough to only make one command to claim all BCH's like:
python claimer.py BCH c7ad778f0197f4750813900d207e6e
e4c416d9f699906074a8a3598a23450c4b PRIV_KEY_OF_
1Pv17qmWEANskhVr4PTNd73sc87CWjMPAh 1Pv17qmWEANskhVr4PTNd73sc87CWjMPAh
BCH_ADDR

C) If I have to make two commands (like A) ), do I have to pay transaction
fees twice?

Would appreciate your answers. Thank you.

With kind regards
Golddouble

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ymgve/bitcoin_fork_claimer/issues/31>, or mute the
thread

**Comment by Golddouble** [comment]
This is a general question. I have the same question also to other Fork coins.

Would anybody be able to answer this question?

**Comment by avialias** [comment]
Two transactions means two separate fee. Claiming process is normal BC
transaction from address that belongs to btc BC to new address that is
generated on bch BC.

Probably you will have option a) two transactions but I'm not contributor
to this git.

**Comment by jamessun** [comment]
@Golddouble I have been successful in using this [fork-helper script](https://gist.github.com/ottoteixeira/c5ba96ff296ddf95b36e498654faf871). Here's the [Reddit thread](https://www.reddit.com/r/BitcoinAirdrops/comments/7uf6dt/i_made_a_simple_python_script_to_help_using/) from the author about the script.

Good luck!

**Comment by ymgve** [comment]
Each transaction claimed takes a new transaction fee, as my script does not support multiple inputs for a transaction. This should generally not be an issue, as the transaction fee is 1000 satoshis in the destination coin, which for fork coins is way less than a cent worth of value.

**Comment by Golddouble** [comment]
Thank you.
