### ISSUE TITLE
fees and satoshis in CDY

### ISSUE THREAD

**Issue by DamnTele** [ymgve/bitcoin_fork_claimer#36]
Hi, 
You stated in the readme file that the default fee in set to 1000 sat, I was wondering if that is sat/byte or if that is sat/kilobyte. I would assume it's per kilobyte but I wanted to ask and make sure.

And I'm looking to claim CDY which is x1000 the BCH  and because I have to do that in standalone mode and specify the number of satoshis do I put that in BCH or CDY?  ie. 362,711,623 vs 362,711,623,000

this the transaction ID I'm trying to claim from by the way, on the [BCH explorer](https://explorer.bitcoin.com/bch/tx/637fe1a2ff34dda57441f705bab825d8e471354bf970cb1ecab370243a26eadb)  and the [CDY explorer](https://block.cdy.one/tx/637fe1a2ff34dda57441f705bab825d8e471354bf970cb1ecab370243a26eadb)

Thank you.

**Comment by ymgve** [comment]
It is 1000 sat in total. Size doesn't matter. The forkcoins have so few transactions that as long as the fee is above the network's minimum, your transaction will be included.

With CDY, the x1000 is just a GUI change by shifting the decimal point. That is, one CDY is 100000 satoshis instead of one BCH being 100000000 satoshis. So in your case, 362711623 satoshis.
