### ISSUE TITLE
Half the amount

### ISSUE THREAD

**Issue by Peeesss** [ymgve/bitcoin_fork_claimer#65]
Hi, after some elusive time fiddling around... I got the script working for SBTC (had an earlier version and found it missing "self.versionno = 70017" ; pfffff ;-)
But anyway.. it worked, great piece of work;
BUT....
When I check my address via https://btcdiv.com/ I get: 12.97806829 SuperBitcoin to claim
When I check my address via fork-helper.py I get:  6.48790590 SBTC to claim
When I execute the fork_claimer script: it successfully obtained 6.48742589 SBTC using all TXIDs found with fork-helper.py !?
THEN I check my address via https://btcdiv.com/ again... and see: 0 SuperBitcoin to claim left !?!?!
THUS somewhere something doesnt add up?
Is anyone having the same observation? what could be intervening?
I do not see anything weird in the script, thus I am at a lost here.
Rgds,
Poul

**Comment by ymgve** [comment]
What's the address you claimed from?

**Comment by Peeesss** [comment]
The address is: 1Gz3ebJYMy6GMXoVia2viUS5TUZ7Rrr3sj

**Comment by ymgve** [comment]
Not sure if they recently changed it, but the blockchain.info API only returns the latest 50 transactions. Since your address has a lot of transactions, most of them aren't visible to the fork helper script.

The helper script is not made or supported by me, so the issue will be closed, but if you can do a bit of coding, look into adding the `&offset=X` parameter to the URL in the helper script manually until you've found all your transactions.

**Comment by Peeesss** [comment]
Herewith another great THNX! yip you were correct... missed the remaining (>50) TXIDS; blockchain indeed has a limit of 50 transactions at a time; will post this on the fork-helper as well!
Only still confused that btcdiv did not report remaining balance left!?
Anyway I am gratefully helped!
