### ISSUE TITLE
Manually create a wallet for each forked coin before running the script?

### ISSUE THREAD

**Issue by torbengb** [ymgve/bitcoin_fork_claimer#66]
Having read the README.md, it's clear to me how to use the script itself. But I'm still unsure of exact steps *around* using this script, specifically the destination address: This may sound stupid but **do I have to manually create a wallet for each forked coin**, and specify that wallet's public address in the script's command? 

I'm just asking because "findmycoins.ninja" tells me I have unclaimed amounts in around 15 different forks and I assume I would have to manually create 15 corresponding wallets. Before I do that tedious task, can you confirm that I'm right? I really do have to manually create a wallet for each forked coin?

**Comment by forkdrop** [comment]
At forkdrop.io, we have a large collection of guides that specifically reference this tool. This one hopefully covers some of your questions: https://forkdrop.io/preparing-to-use-bitcoin-fork-claimer-tool

If your plan is to sell the forks, creating a deposit address for an exchange is an acceptable destination address. Otherwise, if you are planning on holding the coins on different addresses, then yes you will have to create a new wallet address.

**Comment by torbengb** [comment]
Thank you for that link - it is truly detailed and very newbie-friendly.
